import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import SidebarBrandIntro from "@/components/global/SidebarBrandIntro";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <div
            className="grid grid-cols-[minmax(0,1fr)_480px_minmax(0,1fr)] max-h-screen overflow-clip"
            style={{
              background:
                "radial-gradient(87.04% 87.04% at 52.94% 31.51%, #E6EFFA 0%, #888D94 100%)",
            }}
          >
            <div className="relative overflow-x-hidden mr-12">
              <div className="absolute right-0 bottom-0 hidden lg:block h-screen">
                {/* <SidebarBrandIntro /> */}
              </div>
            </div>
            <main className="flex overflow-y-auto bg-white min-h-screen max-h-screen">
              <div className="w-dvw md:w-full">{children}</div>
            </main>
            <div></div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
